<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-OO97RQ9" failures="2" tests="2" name="Default test(failed)" time="0.045" errors="0" timestamp="08 Dec 2024 11:18:53 GMT">
  <testcase classname="com.testng.B" name="test3" time="0.016">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at com.testng.B.test3(B.java:20)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="com.testng.B" name="test4" time="0.002">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at com.testng.B.test4(B.java:26)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="com.testng.B" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
  <testcase classname="com.testng.B" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
  <testcase classname="com.testng.B" name="test5" time="0.0">
    <ignored/>
  </testcase> <!-- test5 -->
</testsuite> <!-- Default test(failed) -->
